baseURL = "https://miriclereach.com/"
title = "MiricleReach"
theme = "PaperMod"
languageCode = "en-GB"
enableRobotsTXT = true
canonifyURLs = false
relativeURLs = true

[pagination]
  pagerSize = 10

[taxonomies]
  category = "categories"
  tag = "tags"

# ---------- Theme Params ----------
[params]
  author            = "Tarik Miri"
  description       = "Cloud & Software Transformation Leader — lessons from scaling systems across time zones."
  defaultTheme      = "auto"         
  ShowReadingTime   = true
  ShowPostNavLinks  = true
  showBreadCrumbs   = false
  ShowCodeCopyButtons = true
  showtoc           = true
  tocopen           = false
  images            = ["/images/og-default.png"]
  hideFooter    = false
  hideCopyright = false
  hideThemeName = true
  comments = true

  [params.giscus]
  repo = "Aktorius/miriclereach-comments"
  repoID = "R_kgDOPntN-g"        # paste from giscus.app
  category = "General"          # the exact category name
  categoryID = "DIC_kwDOPntN-s4Cu08g"  # paste from giscus.app
  mapping = "pathname"
  reactions = true
  emitMetadata = false
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"
  loading = "lazy"

  [params.profileMode]
    enabled     = true
    title       = "MiricleReach"
    subtitle    = "Cloud Architecture • Software Development • DevOps • Engineering Leadership"
    imageUrl    = "/images/about/profile.png"
    imageWidth  = 160
    imageHeight = 160
    imageTitle  = "Tarik Miri"
    buttons = [
      { name = "Cloud Architecture",           url = "/cloud/" },
      { name = "Software Development",         url = "/development/" },
      { name = "DevOps",                       url = "/devops/" },
      { name = "Engineering Leadership",       url = "/leadership/" },
      { name = "About",                        url = "/about/" }
    ]

[[params.socialIcons]]
name = "linkedin"
url  = "https://www.linkedin.com/in/tarikmiri"

[[params.socialIcons]]
name = "github"
url  = "https://github.com/Aktorius"

[[params.socialIcons]]
name = "email"
url  = "mailto:tarmiri@outlook.com"

[menu]
  [[menu.main]] 
    name="Cloud Architecture" 
    url="/cloud/"
    weight=1
  [[menu.main]]
    name="Development"
    url="/development/"
    weight=2
  [[menu.main]] 
    name="DevOps" 
    url="/devops/" 
    weight=3
  [[menu.main]] 
    name="Engineering Leadership" 
    url="/engineering-leadership/" 
    weight=4
  [[menu.main]] 
    name="About" 
    url="/about/" 
    weight=5

[markup]
  [markup.highlight]
    lineNos = true
    style   = "github"

  # Allow raw HTML in Markdown if you embed custom blocks
  [markup.goldmark.renderer]
    unsafe = true